Master:
  ImageTag: "2.141"
  ServiceType: NodePort
  NodePort: 32222

  UseSecurity: false

  InstallPlugins:
    - kubernetes:1.12.4
    - workflow-aggregator:2.5
    - credentials-binding:1.16
    - git:3.9.1
    - blueocean:1.8.2
    - timestamper:1.8.10
    - greenballs:1.15
    - cobertura:1.12.1

  ScriptApproval:
    - method groovy.json.JsonSlurperClassic parseText java.lang.String
    - method java.util.Collection toArray
    - method org.jenkinsci.plugins.workflow.support.actions.EnvironmentAction getEnvironment
    - new groovy.json.JsonSlurperClassic
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods first java.lang.Object[]
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String
    - staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedCall java.lang.Object boolean boolean java.lang.String java.lang.Object[]
    - staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedGetProperty java.lang.Object boolean boolean java.lang.Object

  InitScripts:
    JobRelationshipManager: |-
      import jenkins.model.Jenkins
      import org.jenkinsci.plugins.workflow.job.WorkflowJob
      import hudson.plugins.git.GitSCM

      def jobs = hudson.model.Hudson.instance.getAllItems(org.jenkinsci.plugins.workflow.job.WorkflowJob)*.fullName

      if('JobRelationshipManager' in jobs) {
        println 'JobRelationshipManager already defined'
      } else {
        WorkflowJob job = Jenkins.instance.createProject(WorkflowJob, 'JobRelationshipManager')
        GitSCM scm = new GitSCM("/code/jobrm/websiteui")
        
        def flowDefinition = new org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition(scm, "Jenkinsfile.local")
        job.definition = flowDefinition
      }
      
      if('JobRM API - Lumen' in jobs) {
        println 'JobRM API - Lumen already defined'
      } else {
        WorkflowJob job = Jenkins.instance.createProject(WorkflowJob, 'JobRM API - Lumen')
        GitSCM scm = new GitSCM("/code/jobrm/websiteapi-lumen")
        
        def flowDefinition = new org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition(scm, "Jenkinsfile.local")
        job.definition = flowDefinition
      }

      Jenkins.instance.reload()


Agent:
  Enabled: true
  ImageTag: alpine
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
  volumes:
    - type: HostPath
      hostPath: /host_mnt/e/code
      mountPath: /code
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock

rbac:
  install: true

Persistence:
  ExistingClaim: jenkins-pvc
  volumes:
    - name: source-code
      hostPath: 
        path: /host_mnt/e/code
  mounts: 
    - mountPath: /code
      name: source-code

