kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      app: "jenkins"
    matchExpressions:
      - {key: release, operator: In, values: [jenkins]}