Master:
  ImageTag: "2.103"
  ServiceType: NodePort
  ServicePort: 80

  UseSecurity: false

  InstallPlugins:
    - kubernetes:1.1.3
    - workflow-aggregator:2.5
    - credentials-binding:1.14
    - git:3.7.0
    - blueocean:1.4.0
    - timestamper:1.8.9
    - greenballs:1.15
    - filesystem_scm:2.0
    - cobertura:1.12

  ScriptApproval:
    - method groovy.json.JsonSlurperClassic parseText java.lang.String
    - method java.util.Collection toArray
    - method org.jenkinsci.plugins.workflow.support.actions.EnvironmentAction getEnvironment
    - new groovy.json.JsonSlurperClassic
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods first java.lang.Object[]
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map
    - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String
    - staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedCall java.lang.Object boolean boolean java.lang.String java.lang.Object[]
    - staticMethod org.kohsuke.groovy.sandbox.impl.Checker checkedGetProperty java.lang.Object boolean boolean java.lang.Object

  InitScripts:
    reportautomation: |-
      import jenkins.model.Jenkins
      import org.jenkinsci.plugins.workflow.job.WorkflowJob
      import hudson.plugins.git.GitSCM

      WorkflowJob job = Jenkins.instance.createProject(WorkflowJob, 'JobRelationshipManager')
      GitSCM scm = new GitSCM("/code/jobrm/websiteui")
       
      def flowDefinition = new org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition(scm, "Jenkinsfile.local")
      job.definition = flowDefinition

      Jenkins.instance.reload()

Agent:
  Enabled: true
  ImageTag: alpine
  volumes:
    - type: HostPath
      hostPath: /code
      mountPath: /code
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock

rbac:
  install: true

Persistence:
  size: 2Gi
  volumes:
    - name: source-code
      hostPath: 
        path: /code
  mounts: 
    - mountPath: /code
      name: source-code